baseline:
  classifier: catboost
  n_samples: 1000
  ratio: 1
  result_pth: results/baseline-exp.csv
  sampler_name: adasyn
  score_avg_method: weighted
logger:
  logger_dir: .log
  logger_name: baseline-exp
