baseline:
  classifier: decision_tree
  n_samples: 1000
  ratio: 30
  result_pth: results/baseline-exp.csv
  sampler_name: baseline
  score_avg_method: weighted
logger:
  logger_dir: .log
  logger_name: baseline-exp
