logger:
  log_path: .log
  logger_path: .log
  name: mcmc
  telegram_handler: true
mcmc:
  classifier: gbc
  dataset: balance
  max_iter: 50
  result_pth: results/mcmc.csv
  sampler_d: lr
  score_avg_method: macro
  step_size: 0.25
