logger:
  logger_dir: .log
  logger_name: mcmc
mcmc:
  classifier: catboost
  dataset: breast-cancer
  max_iter: 50
  result_pth: results/mcmc.csv
  sampler_d: lr
  score_avg_method: weighted
  step_size: 0.25
