logger:
  log_path: .log
  name: mcmc
  telegram_handler: false
mcmc:
  classifier: lr
  dataset: frogs
  max_iter: 10
  result_pth: results/mcmc.csv
  sampler_d: lr
  score_avg_method: macro
  step_size: 0.25
