mcmc:
  dataset: heart_2cl
  sampler_d: lr
  max_iter: 50
  step_size: .25
  classifier: svm
  score_avg_method: binary
  
  # Path to result file
  result_pth: results/dev.csv

logger:
  logger_name: mcmc 
  logger_dir: .log
