baseline:
  classifier: knn
  dataset: balance
  result_pth: results/baseline.csv
  sampler_name: instance-hardness-threshold
  score_avg_method: weighted
logger:
  logger_dir: .log
  logger_name: baseline
