baseline:
  classifier: catboost
  dataset: balance
  result_pth: results/baseline.csv
  sampler_name: smotenn
  score_avg_method: macro
logger:
  log_path: .log
  name: baseline
  telegram_handler: false
