baseline:
  classifier: decision_tree
  dataset: breast-tissue
  result_pth: results/baseline.csv
  sampler_name: svm-smote
  score_avg_method: weighted
logger:
  logger_dir: .log
  logger_name: baseline
