baseline:
  classifier: catboost
  dataset: breast-cancer
  result_pth: results/baseline.csv
  sampler_name: instance-hardness-threshold
  score_avg_method: macro
logger:
  log_path: .log
  name: mcmc
  telegram_handler: true
