baseline:
  classifier: gbc
  dataset: breast-tissue
  result_pth: results/baseline.csv
  sampler_name: adasyn
  score_avg_method: macro
logger:
  log_path: .log
  name: mcmc
  telegram_handler: true
