baseline:
  classifier: decision_tree
  dataset: breast-tissue
  result_pth: results/baseline.csv
  sampler_name: kmean-smote
  score_avg_method: macro
logger:
  logger_dir: .log
  logger_name: baseline
