baseline:
  classifier: catboost
  dataset: connectionist
  result_pth: results/baseline.csv
  sampler_name: baseline
  score_avg_method: macro
logger:
  log_path: .log
  name: mcmc
  telegram_handler: true
