baseline:
  classifier: knn
  dataset: ecoli
  result_pth: results/baseline.csv
  sampler_name: instance-hardness-threshold
  score_avg_method: macro
logger:
  log_path: .log
  name: baseline
  telegram_handler: false
