baseline:
  classifier: decision_tree
  dataset: ecoli
  result_pth: results/baseline.csv
  sampler_name: smotenn
  score_avg_method: macro
logger:
  log_path: .log
  name: mcmc
  telegram_handler: true
