baseline:
  classifier: svm
  dataset: frogs
  result_pth: results/baseline.csv
  sampler_name: svm-smote
  score_avg_method: macro
logger:
  log_path: .log
  name: baseline
  telegram_handler: false
