baseline:
  classifier: knn
  dataset: heart_2cl
  result_pth: results/baseline.csv
  sampler_name: baseline
  score_avg_method: macro
logger:
  log_path: .log
  name: baseline
  telegram_handler: false
