baseline:
  classifier: decision_tree
  dataset: ionosphere
  result_pth: results/baseline.csv
  sampler_name: kmean-smote
  score_avg_method: macro
logger:
  log_path: .log
  name: mcmc
  telegram_handler: true
