baseline:
  classifier: svm
  dataset: ionosphere
  result_pth: results/baseline.csv
  sampler_name: instance-hardness-threshold
  score_avg_method: macro
logger:
  logger_dir: .log
  logger_name: baseline
