baseline:
  classifier: mlp
  dataset: ionosphere
  result_pth: results/baseline.csv
  sampler_name: adasyn
  score_avg_method: macro
logger:
  logger_dir: .log
  logger_name: baseline
  logger_path: .log
  name: mcmc
  telegram_handler: true
