baseline:
  classifier: decision_tree
  dataset: parkinsons
  result_pth: results/baseline.csv
  sampler_name: kmean-smote
  score_avg_method: weighted
logger:
  logger_dir: .log
  logger_name: baseline
