dataset:
  batch_size: 64
  name: breast-tissue
  num_workers: 4
  val_split: 0.2
logger:
  logger_dir: .log
  logger_name: breast-tissue
model:
  decoder:
  - - 16
    - relu
  - - 8
    - relu
  - - 16
    - relu
  encoder:
  - - 16
    - relu
  - - 8
    - relu
  - - 16
    - relu
  input_dim: 8
  n_class: 6
  z_dim: 8
oversampling:
  checkpoint_fn: breast-tissue
  checkpoint_pth: checkpoints/breast-tissue
  classifier: knn
  dataset: breast-tissue
  decoder:
  - - 16
    - relu
  - - 8
    - relu
  - - 16
    - relu
  encoder:
  - - 16
    - relu
  - - 8
    - relu
  - - 16
    - relu
  input_dim: 8
  n_class: 6
  result_pth: results/all.csv
  score_avg_method: weighted
  z_dim: 8
training:
  checkpoint_fn: breast-tissue
  checkpoint_monitor: valid-loss
  checkpoint_pth: checkpoints/breast-tissue
  exp_name: breast-tissue
  max_epochs: 100
