dataset:
  batch_size: 16
  name: connectionist
  num_workers: 4
  val_split: 0.2
logger:
  logger_dir: .log
  logger_name: connectionist
model:
  decoder:
  - - 16
    - relu
  - - 8
    - relu
  - - 16
    - relu
  encoder:
  - - 16
    - relu
  - - 8
    - relu
  - - 16
    - relu
  input_dim: 60
  n_class: 2
  z_dim: 8
oversampling:
  checkpoint_fn: connectionist
  checkpoint_pth: checkpoints/connectionist
  classifier: mlp
  dataset: connectionist
  decoder:
  - - 16
    - relu
  - - 8
    - relu
  - - 16
    - relu
  encoder:
  - - 16
    - relu
  - - 8
    - relu
  - - 16
    - relu
  input_dim: 60
  n_class: 2
  result_pth: results/all.csv
  score_avg_method: binary
  z_dim: 8
training:
  checkpoint_fn: connectionist
  checkpoint_monitor: valid-loss
  checkpoint_pth: checkpoints/connectionist
  exp_name: connectionist
  max_epochs: 100
