dataset:
  batch_size: 8
  name: parkinsons
  num_workers: 4
  val_split: 0.2
logger:
  logger_dir: .log
  logger_name: parkinsons
model:
  decoder:
  - - 16
    - relu
  - - 8
    - relu
  - - 16
    - relu
  encoder:
  - - 16
    - relu
  - - 8
    - relu
  - - 16
    - relu
  input_dim: 22
  n_class: 2
  z_dim: 8
oversampling:
  checkpoint_fn: parkinsons
  checkpoint_pth: checkpoints/parkinsons
  classifier: mlp
  dataset: parkinsons
  decoder:
  - - 16
    - relu
  - - 8
    - relu
  - - 16
    - relu
  encoder:
  - - 16
    - relu
  - - 8
    - relu
  - - 16
    - relu
  input_dim: 22
  n_class: 2
  result_pth: results/all.csv
  score_avg_method: binary
  z_dim: 8
training:
  checkpoint_fn: parkinsons
  checkpoint_monitor: valid-loss
  checkpoint_pth: checkpoints/parkinsons
  exp_name: parkinsons
  max_epochs: 100
