mcmc:
  dataset: heart_2cl
  sampler_d: lr
  max_iter: 50
  step_size: .25
  classifier: mlp
  score_avg_method: macro 
  
  # Path to result file
  result_pth: results/mcmc.csv

logger:
  name: mcmc 
  log_path: .log
  telegram_handler : true
