dataset:
  name: breast-cancer 
  batch_size: 8
  num_workers: 4
  val_split: 0.2

model:
  input_dim: 30
  encoder: 
    - [16, 'relu']
    - [8, 'relu']
    - [16, 'relu']
  decoder: 
    - [16, 'relu']
    - [8, 'relu']
    - [16, 'relu']
  z_dim: 8
  n_class: 2

training:
  exp_name: breast-cancer 
  max_epochs: 100
  checkpoint_pth: checkpoints/breast-cancer
  checkpoint_fn: breast-cancer 
  checkpoint_monitor: valid-loss 


oversampling:
  dataset: breast-cancer 
  classifier: mlp 

  # cvae params 
  checkpoint_pth: checkpoints/breast-cancer
  checkpoint_fn: breast-cancer 
  input_dim: 30
  encoder: 
    - [16, 'relu']
    - [8, 'relu']
    - [16, 'relu']
  decoder: 
    - [16, 'relu']
    - [8, 'relu']
    - [16, 'relu']
  z_dim: 8
  n_class: 2

  # evaluation metrics
  score_avg_method: binary 

  # Path to result file
  result_pth: results/breast-cancer.csv

logger:
  logger_name: breast-cancer 
  logger_dir: .log
