baseline:
  sampler_name: baseline

  # Synthetic dataset config
  n_samples: 1000
  ratio: 2

  # Classifier config
  classifier: mlp

  # evaluation params
  score_avg_method: binary 
  
  # Path to result file
  result_pth: results/baseline-exp.csv

logger:
  logger_name: baseline-exp 
  logger_dir: .log

