baseline:
  dataset: heart_2cl
  sampler_name: baseline
  classifier: mlp

  # evaluation params
  score_avg_method: binary 
  
  # Path to result file
  result_pth: results/baseline.csv

logger:
  name: baseline 
  log_path: .log
  telegram_handler: false

