dataset:
  name: ionosphere
  batch_size: 4
  num_workers: 6
  val_split: 0.2

model:
  input_dim: 32
  encoder: 
    - [16, 'relu']
    - [8, 'relu']
    - [16, 'relu']
  decoder: 
    - [16, 'relu']
    - [8, 'relu']
    - [16, 'relu']
  z_dim: 8
  n_class: 2

training:
  exp_name: dev
  max_epochs: 100
  checkpoint_pth: checkpoints/dev 
  checkpoint_fn: ionosphere
  checkpoint_monitor: valid-loss 


oversampling:
  dataset: ionosphere
  classifier: lr 

  # cvae params 
  checkpoint_pth: checkpoints/dev 
  checkpoint_fn: ionosphere-v2
  input_dim: 32
  encoder: 
    - [16, 'relu']
    - [8, 'relu']
    - [16, 'relu']
  decoder: 
    - [16, 'relu']
    - [8, 'relu']
    - [16, 'relu']
  z_dim: 8
  n_class: 2

  # evaluation metrics
  score_avg_method: binary

  # Path to result file
  result_pth: results/dev.csv

logger:
  logger_name: dev
  logger_dir: .log
