dataset:
  name: ecoli 
  batch_size: 4
  num_workers: 1
  val_split: 0.2

model:
  input_dim: 7
  encoder: 
    - [16, 'relu']
    - [8, 'relu']
    - [16, 'relu']
  decoder: 
    - [16, 'relu']
    - [8, 'relu']
    - [16, 'relu']
  z_dim: 8
  n_class: 2

training:
  exp_name: ecoli 
  max_epochs: 100
  checkpoint_pth: checkpoints/ecoli
  checkpoint_fn: ecoli 
  checkpoint_monitor: valid-loss 


oversampling:
  dataset: ecoli 
  classifier: lr 

  # cvae params 
  checkpoint_pth: checkpoints/ecoli
  checkpoint_fn: ecoli
  input_dim: 7
  encoder: 
    - [16, 'relu']
    - [8, 'relu']
    - [16, 'relu']
  decoder: 
    - [16, 'relu']
    - [8, 'relu']
    - [16, 'relu']
  z_dim: 8
  n_class: 2

  # evaluation metrics
  score_avg_method: binary 

  # Path to result file
  result_pth: results/ecoli.csv

logger:
  logger_name: ecoli 
  logger_dir: .log
