dataset:
  name: frogs
  batch_size: 64
  num_workers: 6
  val_split: 0.2

model:
  input_dim: 22
  encoder: 
    - [16, 'relu']
    - [8, 'relu']
    - [16, 'relu']
  decoder: 
    - [16, 'relu']
    - [8, 'relu']
    - [16, 'relu']
  z_dim: 8
  n_class: 2

training:
  exp_name: frogs 
  max_epochs: 100
  checkpoint_pth: checkpoints/frogs
  checkpoint_fn: frogs 
  checkpoint_monitor: valid-loss 


oversampling:
  dataset: frogs 
  classifier: svm 

  # cvae params 
  checkpoint_pth: checkpoints/frogs
  checkpoint_fn: frogs
  input_dim: 22
  encoder: 
    - [16, 'relu']
    - [8, 'relu']
    - [16, 'relu']
  decoder: 
    - [16, 'relu']
    - [8, 'relu']
    - [16, 'relu']
  z_dim: 8
  n_class: 2

  # evaluation metrics
  score_avg_method: binary 

  # Path to result file
  result_pth: results/ecoli.csv

logger:
  logger_name: frogs 
  logger_dir: .log
