dataset:
  name: parkinsons 
  batch_size: 8
  num_workers: 4
  val_split: 0.2

model:
  input_dim: 22
  encoder: 
    - [16, 'relu']
    - [8, 'relu']
    - [16, 'relu']
  decoder: 
    - [16, 'relu']
    - [8, 'relu']
    - [16, 'relu']
  z_dim: 8
  n_class: 2

training:
  exp_name: parkinsons 
  max_epochs: 100
  checkpoint_pth: checkpoints/parkinsons
  checkpoint_fn: parkinsons 
  checkpoint_monitor: valid-loss 


oversampling:
  dataset: parkinsons 
  classifier: svm 

  # cvae params 
  checkpoint_pth: checkpoints/parkinsons
  checkpoint_fn: parkinsons 
  input_dim: 22
  encoder: 
    - [16, 'relu']
    - [8, 'relu']
    - [16, 'relu']
  decoder: 
    - [16, 'relu']
    - [8, 'relu']
    - [16, 'relu']
  z_dim: 8
  n_class: 2

  # evaluation metrics
  score_avg_method: binary

  # Path to result file
  result_pth: results/parkinsons.csv

logger:
  logger_name: parkinsons 
  logger_dir: .log
