logger:
  logger_dir: .log
  logger_name: mcmc_exp
mcmc:
  classifier: gbc
  max_iter: 50
  n_samples: 1000
  ratio: 1
  result_pth: results/mcmc_exp.csv
  sampler_d: lr
  score_avg_method: binary
  step_size: 0.25
