baseline:
  classifier: lr
  n_samples: 1000
  ratio: 10
  result_pth: results/baseline-exp.csv
  sampler_name: instance-hardness-threshold
  score_avg_method: weighted
logger:
  logger_dir: .log
  logger_name: baseline-exp
