baseline:
  classifier: mlp
  n_samples: 1000
  ratio: 6
  result_pth: results/baseline-exp.csv
  sampler_name: instance-hardness-threshold
  score_avg_method: binary
logger:
  logger_dir: .log
  logger_name: baseline-exp
