baseline:
  classifier: catboost
  n_samples: 1000
  ratio: 7
  result_pth: results/baseline-exp.csv
  sampler_name: kmean-smote
  score_avg_method: binary
logger:
  logger_dir: .log
  logger_name: baseline-exp
