baseline:
  classifier: lr
  n_samples: 1000
  ratio: 5
  result_pth: results/baseline-exp.csv
  sampler_name: kmean-smote
  score_avg_method: weighted
logger:
  logger_dir: .log
  logger_name: baseline-exp
